version: "3.8"
services:
  backend:
    build: .
    container_name: faq-backend
    ports:
      - "5000:5000"
    environment:
      - NODE_ENV=production
      - MONGO_URI=mongodb://mongo:27017/faq_db
      - REDIS_HOST=redis
      - REDIS_PORT=6379
    depends_on:
      - mongo
      - redis

  mongo:
    image: mongo:latest
    container_name: faq-db
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db

  redis:
    image: redis:latest
    container_name: faq-redis
    ports:
      - "6379:6379"

volumes:
  mongodb_data:
